### ISSUE TITLE
Services not stopped after `dapr stop` - windows-specific

### ISSUE THREAD

**Issue by huzhiguan** [dapr/cli#222]
## Expected Behavior

Testing with samples from `https://github.com/dapr/samples/tree/master/1.hello-world`. On step7, the `pythonapp` and `nodeapp` should stop after:
`dapr stop --app-id nodeapp`
`dapr stop --app-id pythonapp`

## Actual Behavior

After entering` dapr stop --app-id pythonapp`, the `nodeapp` still got new orders. I made sure that the `pythonapp` that was running inside a powershell was stopped at that time.
Then I entered `dapr stop --app-id nodeapp`, the process inside powershell stopped:
```
PS D:\Workspace\dapr\samples\1.hello-world> dapr stop --app-id nodeapp
app stopped successfully
PS D:\Workspace\dapr\samples\1.hello-world>
```
and
```
PS D:\Workspace\dapr\samples\1.hello-world> dapr run --app-id nodeapp --app-port 3000 --port 3500 node app.js
Starting Dapr with id nodeapp. HTTP Port: 3500. gRPC Port: 57271
You're up and running! Both Dapr and your app logs will appear here.

[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="starting Dapr Runtime -- version 0.3.0 -- commit v0.3.0-rc.0-1-gfe6c306-dirty"
[0m[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="log level set to: info"
[0m[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="standalone mode configured"
[0m[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="dapr id: nodeapp"
[0m[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="loaded component messagebus (pubsub.redis)"
[0m[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="loaded component statestore (state.redis)"
[0m[93;1m== DAPR == time="2019-12-16T16:15:27-06:00" level=info msg="application protocol: http. waiting on port 3000"
[0m[94;1m== APP == Node App listening on port 3000!
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="application discovered on port 3000"
[0m[93;1m== DAPR == 2019-12-16 16:15:28.087742 I | redis: connecting to localhost:6379
[0m[93;1m== DAPR == 2019-12-16 16:15:28.592746 I | redis: connected to localhost:6379 (localAddr: 127.0.0.1:57278, remAddr: 127.0.0.1:6379)
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="Initialized service discovery to standalone"
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="http server is running on port 3500"
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="gRPC server is running on port 57271"
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="local service entry announced"
[0m[93;1m== DAPR == time="2019-12-16T16:15:28-06:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 1710.0034ms"
[0m[93;1m== DAPR == time="2019-12-16T16:15:29-06:00" level=info msg="actors: established connection to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2019-12-16T16:15:29-06:00" level=info msg="actors: placement order received: lock"
[0m[93;1m== DAPR == time="2019-12-16T16:15:29-06:00" level=info msg="actors: placement order received: update"
[0m[93;1m== DAPR == time="2019-12-16T16:15:29-06:00" level=info msg="actors: placement tables updated"
[0m[93;1m== DAPR == time="2019-12-16T16:15:29-06:00" level=info msg="actors: placement order received: unlock"
[0m
PS D:\Workspace\dapr\samples\1.hello-world>
```
Ran `dapr list`:
```
PS D:\Workspace\dapr\samples\1.hello-world> dapr list
No Dapr instances found.
```
But I was still able to get responses after sending a request 
`GET http://localhost:3500/v1.0/invoke/nodeapp/method/order`.
I can still see them in the TaskManager:
![image](https://user-images.githubusercontent.com/961144/70948154-6ee89500-2020-11ea-8ab3-749ddbd90aae.png)

I tried to restart the service, and it gave me an error which seems like the address was still in use:

```PS D:\Workspace\dapr\samples\1.hello-world> dapr run --app-id nodeapp --app-port 3000 --port 3500 node app.js
Starting Dapr with id nodeapp. HTTP Port: 3500. gRPC Port: 56060
You're up and running! Both Dapr and your app logs will appear here.

[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="starting Dapr Runtime -- version 0.3.0 -- commit v0.3.0-rc.0-1-gfe6c306-dirty"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="log level set to: info"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="standalone mode configured"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="dapr id: nodeapp"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="loaded component messagebus (pubsub.redis)"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="loaded component statestore (state.redis)"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="application protocol: http. waiting on port 3000"
[0m[93;1m== DAPR == time="2019-12-16T15:00:13-06:00" level=info msg="application discovered on port 3000"
[0m[93;1m== DAPR == 2019-12-16 15:00:13.656738 I | redis: connecting to localhost:6379
[0m[93;1m== DAPR == 2019-12-16 15:00:14.158741 I | redis: connected to localhost:6379 (localAddr: 127.0.0.1:56064, remAddr: 127.0.0.1:6379)
[0m[94;1m== APP == events.js:183
[0m[94;1m== APP ==       throw er; // Unhandled 'error' event
[0m[94;1m== APP ==       ^
[0m[94;1m== APP ==
[0m[94;1m== APP == Error: listen EADDRINUSE :::3000
[0m[94;1m== APP ==     at Object._errnoException (util.js:992:11)
[0m[94;1m== APP ==     at _exceptionWithHostPort (util.js:1014:20)
[0m[94;1m== APP ==     at Server.setupListenHandle [as _listen2] (net.js:1355:14)
[0m[94;1m== APP ==     at listenInCluster (net.js:1396:12)
[0m[94;1m== APP ==     at Server.listen (net.js:1480:7)
[0m[94;1m== APP ==     at Function.listen (D:\Workspace\dapr\samples\1.hello-world\node_modules\express\lib\application.js:618:24)
[0m[94;1m== APP ==     at Object.<anonymous> (D:\Workspace\dapr\samples\1.hello-world\app.js:62:5)
[0m[94;1m== APP ==     at Module._compile (module.js:652:30)
[0m[94;1m== APP ==     at Object.Module._extensions..js (module.js:663:10)
[0m[94;1m== APP ==     at Module.load (module.js:565:32)
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="Initialized service discovery to standalone"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="http server is running on port 3500"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="gRPC server is running on port 56060"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="local service entry announced"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 843.0018ms"
[0m[93;1m== DAPR == time="2019-12-16T15:00:14-06:00" level=fatal msg="listen tcp4 :3500: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."
[0m
terminated signal received: shutting down
Error exiting Dapr: TerminateProcess: Access is denied.
Error exiting App: TerminateProcess: Access is denied.
```

## Steps to Reproduce the Problem

Windows 10 Pro, Version 1903, OS Build 18362, 10024
Dapr CLI version: 0.3.0, Runtime version: 0.3.0

Following all the steps here: https://github.com/dapr/samples/tree/master/1.hello-world
Everything worked until Step 7.

**Comment by youngbupark** [comment]
@huzhiguan I cannot reproduce this on my mac. 

@LMWF Can you please try to reproduce on windows machine ?

**Comment by LMWF** [comment]
This does repro on windows.

Here's a slightly different view on it:
I watched what was happening in process explorer.  When the app is running after a first dapr run, node.exe is listed in a process tree with cmd as the root.  After issuing the dapr stop, node.exe disappears from this subtree.  However a netstat -anob | findstr 3000 still shows it exists.  If you scroll to the very bottom of process explorer now, the corresponding node.exe is now listed here, without a parent.  

A subsequent dapr run will observe the error in this issue.  Another dapr run on top of that somehow clears the process and daprd + node.exe start as normal.

I wonder if dapr stop is killing dapr.exe instead of the app.

**Comment by youngbupark** [comment]
@yaron2 @LMWF I think we need to use process group id to kill daprd and app processes.

Please look at this article - https://medium.com/@felixge/killing-a-child-process-and-all-of-its-children-in-go-54079af94773

**Comment by LMWF** [comment]
The solution should just be to add /T to taskkill on Windows.  I'll have a PR soon.

The issue is that dapr stop operates on the dapr instance that is hosting the app we want to stop.  On MacOS/Linux we send kill and dapr has a handler for this to kill its children daprd and app.  On windows, taskkill sends WM_CLOSE.  Rather than handling it the same way as the kill signal handlers, it's easier to just add /T to the taskkill command, which will terminate children processes.
