### ISSUE TITLE
Error invoke actor method on macOS 12.0.1

### ISSUE THREAD

**Issue by kamasylvia** [dapr/cli#837]
## Bug
The code is cloned from [dapr/dotnet-sdk/examples/Actor](https://github.com/dapr/dotnet-sdk/tree/master/examples/Actor), and I run the commands from the README.md of that example.

The server reported an error if we do not set `--components-path` with a state store component configuration. This is easy to be fixed. 

The client reported `Unhandled exception. Dapr.DaprApiException: error invoke actor method: error finding address for actor type DemoActor with id abc`

## Environment
OS: macOS Monterey 12.0.1
Dapr CLI version: 1.3.0
Dapr runtime version: 1.5.0 

## Expected Behavior
The server and client work well. 

## Actual Behavior
Server: 
```sh
$  dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000 dotnet run 

ℹ️  Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 51878
2021/11/17 19:02:50 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
INFO[0000] starting Dapr Runtime -- version 1.5.0 -- commit 83fe579f5dc93bef1ce3b464d3167a225a3aff3a  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] log level set to: info                        app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] metrics server started on :51879/             app_id=demo_actor instance=MacBook-Pro.local scope=dapr.metrics type=log ver=1.5.0
INFO[0000] standalone mode configured                    app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] app id: demo_actor                            app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] local service entry announced: demo_actor -> 198.18.0.1:51883  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.5.0
INFO[0000] Initialized name resolution to mdns           app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] loading components                            app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] waiting for all outstanding components to be processed  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] all outstanding components processed          app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] enabled gRPC tracing middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.api type=log ver=1.5.0
INFO[0000] enabled gRPC metrics middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.api type=log ver=1.5.0
INFO[0000] API gRPC server is running on port 51878      app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] enabled metrics http middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.http type=log ver=1.5.0
INFO[0000] enabled tracing http middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.http type=log ver=1.5.0
INFO[0000] http server is running on port 3500           app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] The request body size parameter is: 4         app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] enabled gRPC tracing middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.internal type=log ver=1.5.0
INFO[0000] enabled gRPC metrics middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.internal type=log ver=1.5.0
INFO[0000] internal gRPC server is running on port 51883  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] application protocol: http. waiting on port 5000.  This will block until the app is listening on that port.  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] application discovered on port 5000           app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] application configuration loaded              app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.actor type=log ver=1.5.0
ERRO[0000] app returned http status code 403 from subscription endpoint  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] dapr initialized. Status: Running. Init Elapsed 34.495ms  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] placement tables updated, version: 14         app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.actor.internal.placement type=log ver=1.5.0
ℹ️  Updating metadata for app command: dotnet run
✅  You're up and running! Both Dapr and your app logs will appear here.

== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Now listening on: http://localhost:5000
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Content root path: /Users/Sylvia/Documents/Tutorials/dotnet-sdk/examples/Actor/DemoActor
```

Client:
```sh
$ dotnet run        
Making call using actor proxy to save data.
Unhandled exception. Dapr.DaprApiException: error invoke actor method: error finding address for actor type DemoActor with id abc
   at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken) in /Users/Sylvia/Documents/Tutorials/dotnet-sdk/src/Dapr.Actors/DaprHttpInteractor.cs:line 393
   at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, CancellationToken cancellationToken) in /Users/Sylvia/Documents/Tutorials/dotnet-sdk/src/Dapr.Actors/DaprHttpInteractor.cs:line 298
   at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithRemotingAsync(ActorMessageSerializersManager serializersManager, IActorRequestMessage remotingRequestRequestMessage, CancellationToken cancellationToken) in /Users/Sylvia/Documents/Tutorials/dotnet-sdk/src/Dapr.Actors/DaprHttpInteractor.cs:line 127
   at Dapr.Actors.Communication.Client.ActorRemotingClient.InvokeAsync(IActorRequestMessage remotingRequestMessage, CancellationToken cancellationToken) in /Users/Sylvia/Documents/Tutorials/dotnet-sdk/src/Dapr.Actors/Communication/Client/ActorRemotingClient.cs:line 39
   at Dapr.Actors.Client.ActorProxy.InvokeMethodAsync(Int32 interfaceId, Int32 methodId, String methodName, IActorRequestMessageBody requestMsgBodyValue, CancellationToken cancellationToken) in /Users/Sylvia/Documents/Tutorials/dotnet-sdk/src/Dapr.Actors/Client/ActorProxy.cs:line 219
   at ActorClient.Program.Main(String[] args) in /Users/Sylvia/Documents/Tutorials/dotnet-sdk/examples/Actor/ActorClient/Program.cs:line 41
   at ActorClient.Program.<Main>(String[] args)
```
## Steps to Reproduce the Problem
1. Clone [dapr/dotnet-sdk](https://github.com/dapr/dotnet-sdk.git)
2. `cd` to `dotnet-sdk/examples/Actors/DemoActor`
3. Run `dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000 dotnet run `
4. `cd` to `dotnet-sdk/examples/Actors/ActorClient`
5. Run `dotnet run`

## Steps to Mitigate the Problem
I found a workaround to mitigate the problem. Because it works, I think this issue should be reported here not `dapr/dotnet-sdk`.

1. `cd` to `dotnet-sdk/examples/Actors/DemoActor`
2. Run `dotnet run`
3. Open a new terminal and `cd` to `dotnet-sdk/examples/Actors/DemoActor`
4. run `dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000`. 
5. `cd` to `dotnet-sdk/examples/Actor/ActorClient`
6. Run `dotnet run`

### Outputs
Server terminal 1:
```sh
$ dotnet run        
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/Sylvia/Documents/Tutorials/dotnet-sdk/examples/Actor/DemoActor
```

Server terminal 2:
```sh
$ dapr run --dapr-http-port 3500 --app-id demo_actor --app-port 5000
WARNING: no application command found.
ℹ️  Starting Dapr with id demo_actor. HTTP Port: 3500. gRPC Port: 54354
2021/11/17 19:36:59 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
INFO[0000] starting Dapr Runtime -- version 1.5.0 -- commit 83fe579f5dc93bef1ce3b464d3167a225a3aff3a  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] log level set to: info                        app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] metrics server started on :54355/             app_id=demo_actor instance=MacBook-Pro.local scope=dapr.metrics type=log ver=1.5.0
INFO[0000] standalone mode configured                    app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] app id: demo_actor                            app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] mTLS is disabled. Skipping certificate request and tls validation  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] local service entry announced: demo_actor -> 198.18.0.1:54359  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.contrib type=log ver=1.5.0
INFO[0000] Initialized name resolution to mdns           app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] loading components                            app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] component loaded. name: pubsub, type: pubsub.redis/v1  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] waiting for all outstanding components to be processed  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] component loaded. name: statestore, type: state.redis/v1  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] all outstanding components processed          app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] enabled gRPC tracing middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.api type=log ver=1.5.0
INFO[0000] enabled gRPC metrics middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.api type=log ver=1.5.0
INFO[0000] API gRPC server is running on port 54354      app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] enabled metrics http middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.http type=log ver=1.5.0
INFO[0000] enabled tracing http middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.http type=log ver=1.5.0
INFO[0000] http server is running on port 3500           app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] The request body size parameter is: 4         app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] enabled gRPC tracing middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.internal type=log ver=1.5.0
INFO[0000] enabled gRPC metrics middleware               app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.grpc.internal type=log ver=1.5.0
INFO[0000] internal gRPC server is running on port 54359  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] application protocol: http. waiting on port 5000.  This will block until the app is listening on that port.  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] application discovered on port 5000           app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] application configuration loaded              app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
INFO[0000] actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.actor type=log ver=1.5.0
INFO[0000] placement tables updated, version: 14         app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.actor.internal.placement type=log ver=1.5.0
INFO[0000] dapr initialized. Status: Running. Init Elapsed 147.185ms  app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime type=log ver=1.5.0
✅  You're up and running! Dapr logs will appear here.

INFO[0002] placement tables updated, version: 15         app_id=demo_actor instance=MacBook-Pro.local scope=dapr.runtime.actor.internal.placement type=log ver=1.5.0
```

Client terminal:
```sh
$ dotnet run
Making call using actor proxy to save data.
Making call using actor proxy to get data.
Received data is PropertyA: ValueA, PropertyB: ValueB.
Making calls to an actor method which has no argument and no return type.
Got Incorrect Exception from actor method invocation. Exception Dapr.Actors.ActorInvokeException: The method or operation is not implemented.
Making calls without Remoting.
Registering the timer and reminder
Waiting so the timer and reminder can be triggered
Making call using actor proxy to get data after timer and reminder triggered
Received data is PropertyA: Timer triggered at '02021-11-17T19:37:41', PropertyB: Reminder triggered at '2021-11-17T19:37:40'.
Deregistering timer. Timers would any way stop if the actor is deactivated as part of Dapr garbage collection.
Deregistering reminder. Reminders are durable and would not stop until an explicit deregistration or the actor is deleted.
Creating a Bank Actor
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥100.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥90.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥80.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥70.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥60.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥50.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥40.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥30.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥20.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥10.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '¥0.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '-¥10.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '-¥20.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '-¥30.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '-¥40.00'.
Withdrawing '¥10.00'...
Balance for account '05613289-b2c5-4b29-b927-7c280d6a4e9d' is '-¥50.00'.
Withdrawing '¥10.00'...
Overdraft: Remote Actor Method Exception
```

**Comment by berndverst** [comment]
This is almost certainly caused by ControlCenter AirPlay receiver. Apple decided to assign the commonly used port 5000 to one of their system services :(

You can deactivate it in System Preferences › Sharing, and unchecking AirPlay Receiver to release port 5000

**Comment by mukundansundar** [comment]
@kamasylvia Does the above solution work for you?

**Comment by kamasylvia** [comment]
> @kamasylvia Does the above solution work for you?

I'm not sure, because I cannot reproduce the issue now. Dapr-cli works well today on my MacBook, whether the AirPlay is activated or not.
