### ISSUE TITLE
Dapr CLI Cannot Upgrade Dapr Cluster on Edge Version

### ISSUE THREAD

**Issue by halspang** [dapr/cli#954]
## Expected Behavior
When a k8s cluster is running an edge version of Dapr, it should be able to be upgraded to a released version.

## Actual Behavior
Instead of upgrading, it panics on a nil pointer when trying to determine if it's an upgrade or downgrade.

## Steps to Reproduce the Problem
1. Deploy Dapr with a locally built (edge) version.
2. Use the Dapr CLI to upgrade to a different version `dapr upgrade -k --runtime-version 1.7.0-rc.3`

```
➜  ~/Workspace/cli git:(master) 
$ dapr status -k
  NAME                   NAMESPACE    HEALTHY  STATUS   REPLICAS  VERSION          AGE  CREATED              
  dapr-operator          dapr-system  True     Running  1         dev-linux-amd64  4d   2022-04-01 16:23.57  
  dapr-placement-server  dapr-system  True     Running  1         dev-linux-amd64  4d   2022-04-01 16:23.57  
  dapr-dashboard         dapr-system  True     Running  1         0.9.0            4d   2022-04-01 16:23.56  
  dapr-sidecar-injector  dapr-system  True     Running  1         dev-linux-amd64  4d   2022-04-01 16:23.58  
  dapr-sentry            dapr-system  True     Running  1         dev-linux-amd64  4d   2022-04-01 16:23.56

➜  ~/Workspace/cli git:(master) 
$ dapr upgrade -k --runtime-version 1.7.0-rc.3
ℹ️  Dapr control plane version dev-linux-amd64 detected in namespace dapr-system
ℹ️  Starting upgrade...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2505ad1]

goroutine 1 [running]:
github.com/hashicorp/go-version.(*Version).String(0x0, 0xc000cb3366, 0xa)
        /Users/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.3.0/version.go:371 +0x51
github.com/hashicorp/go-version.(*Version).Compare(0xc000bcc370, 0x0, 0xc0003da000)
        /Users/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.3.0/version.go:118 +0x51
github.com/hashicorp/go-version.(*Version).LessThan(...)
        /Users/runner/go/pkg/mod/github.com/hashicorp/go-version@v1.3.0/version.go:310
github.com/dapr/cli/pkg/kubernetes.isDowngrade(0x7ff7bfeffaaa, 0xa, 0xc000be7218, 0xf, 0xc0006ac780)
        /Users/runner/work/cli/cli/pkg/kubernetes/upgrade.go:199 +0x8c
github.com/dapr/cli/pkg/kubernetes.Upgrade(0x7ff7bfeffaaa, 0xa, 0x37c9ac0, 0x0, 0x0, 0x12c, 0xc0001cad60, 0x28d940c)
        /Users/runner/work/cli/cli/pkg/kubernetes/upgrade.go:121 +0x599
github.com/dapr/cli/cmd.glob..func21(0x3769ca0, 0xc000714150, 0x0, 0x3)
        /Users/runner/work/cli/cli/cmd/upgrade.go:37 +0xab
github.com/spf13/cobra.(*Command).execute(0x3769ca0, 0xc000714120, 0x3, 0x3, 0x3769ca0, 0xc000714120)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x3769f20, 0xc0000e42a8, 0x1, 0xc0008e5f30)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/dapr/cli/cmd.Execute(0x2b21ce8, 0xa, 0x2b20fe4, 0x3)
        /Users/runner/work/cli/cli/cmd/dapr.go:55 +0x16b
main.main()
        /Users/runner/work/cli/cli/main.go:27 +0x51
```

## Release Note

RELEASE NOTE: **FIX** CLI upgrade command panics on edge versions

**Comment by pravinpushkar** [comment]
I think, it is not always possible to determine upgrade or downgrade case from an edge version. So, it is better to handle the error when it is unable to parse the current version of `dapr` and fail the upgrade here - 
https://github.com/dapr/cli/blob/0c514816cdc5de73bc0106a922103293bf810926/pkg/kubernetes/upgrade.go#L172
as this -
```
existing, err := version.NewVersion(existingVersion) 
if err != nil {
// log error
os.Exit(1)
}

```
@mukundansundar
